name: Autograding

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gcc
        run: sudo apt-get install -y gcc

      - name: Compile project
        run: gcc src/*.c tests/*.c -o test_agenda

      - name: Test buscar contacto
        id: buscar-test
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Buscar contacto
          id: buscar-test
          command: "./test_agenda buscar"
          input: ""
          expected-output: "✅ Buscar contacto: OK"
          comparison-method: substring
          timeout: 10

      - name: Test guardar contacto
        id: guardar-test
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Guardar contacto
          id: guardar-test
          command: "./test_agenda guardar"
          input: ""
          expected-output: "✅ Guardar contacto: OK"
          comparison-method: substring
          timeout: 10

      - name: Test leer contacto
        id: leer-test
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Leer contacto
          id: leer-test
          command: "./test_agenda leer"
          input: ""
          expected-output: "✅ Leer contacto: OK"
          comparison-method: substring
          timeout: 10

      - name: Test imprimir contacto
        id: imprimir-test
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Imprimir contacto
          id: imprimir-test
          command: "./test_agenda imprimir"
          input: ""
          expected-output: "✅ Imprimir contacto: OK"
          comparison-method: substring
          timeout: 10

      - name: Test ordenar contactos
        id: ordenar-test
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Ordenar contactos
          id: ordenar-test
          command: "./test_agenda ordenar"
          input: ""
          expected-output: "✅ Ordenar contactos: OK"
          comparison-method: substring
          timeout: 10

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          BUSCAR-TEST_RESULTS: "${{ steps.buscar-test.outputs.result }}"
          GUARDAR-TEST_RESULTS: "${{ steps.guardar-test.outputs.result }}"
          LEER-TEST_RESULTS: "${{ steps.leer-test.outputs.result }}"
          IMPRIMIR-TEST_RESULTS: "${{ steps.imprimir-test.outputs.result }}"
          ORDENAR-TEST_RESULTS: "${{ steps.ordenar-test.outputs.result }}"
        with:
          runners: buscar-test, guardar-test, leer-test, imprimir-test, ordenar-test
